const app = document.querySelector('#app');
let state = null;
let activeView = 'overview';
let activeRoomId = null;
const icons = { check: '✓', up: '↗', join: '+' };
const identityKey = 'habit-arena-identity';
function getIdentity() { try { return JSON.parse(localStorage.getItem(identityKey)) || null; } catch { return null; } }
function createIdentity(name) { const cleanName = name.trim(); const id = globalThis.crypto?.randomUUID?.() || `user-${Date.now()}-${Math.random().toString(36).slice(2)}`; const identity = { id, name: cleanName, initials: cleanName.split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase() }; localStorage.setItem(identityKey, JSON.stringify(identity)); return identity; }
function applyIdentity(identity) { if (state) { state.user = { ...state.user, ...identity }; if (!inviteRoom()) state.rooms.forEach(room => room.leaderboard?.forEach(player => { if (player.you && !player.userId) { player.name = identity.name; player.initials = identity.initials; player.userId = identity.id; } })); saveLocalState(); } const sidebarName = document.querySelector('#sidebar-name'); const topName = document.querySelector('#top-name'); if (sidebarName) sidebarName.textContent = identity.name; if (topName) topName.textContent = identity.name; document.querySelectorAll('.profile-mini .avatar, .user-chip .avatar').forEach(element => { element.textContent = identity.initials; }); }
function inviteRoom() { return new URLSearchParams(window.location.search).get('room'); }
function openIdentityModal() { document.querySelector('#modal-root').innerHTML = '<div class="modal-backdrop"><div class="modal"><div class="modal-header"><h2>Choose your arena name</h2></div><form class="form" id="identity-form"><p style="margin:0;color:var(--muted);font-size:12px;line-height:1.5">Your name identifies you in rooms and invite links. It stays on this device until you change it.</p><label>Your unique name<input name="name" placeholder="e.g. Alex Morgan" autocomplete="nickname" minlength="2" maxlength="32" required autofocus></label><div class="form-actions"><button class="primary-btn">Enter arena →</button></div></form></div></div>'; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function openProfileModal() { const identity = getIdentity() || state.user; document.querySelector('#modal-root').innerHTML = `<div class="modal-backdrop" data-action="close-modal"><div class="modal"><div class="modal-header"><h2>Your profile</h2><button type="button" class="close-btn" data-action="close-modal">×</button></div><form class="form" id="profile-form"><label>Display name<input name="name" value="${escapeHtml(identity.name)}" minlength="2" maxlength="32" required></label><div class="form-actions"><button type="button" class="secondary-btn" data-action="sign-out">Reset identity</button><button class="primary-btn">Save profile →</button></div></form></div></div>`; }
function openSettingsModal() { document.querySelector('#modal-root').innerHTML = '<div class="modal-backdrop" data-action="close-modal"><div class="modal"><div class="modal-header"><h2>Settings</h2><button type="button" class="close-btn" data-action="close-modal">×</button></div><div class="form"><p style="margin:0;color:var(--muted);font-size:12px;line-height:1.5">Your profile and activity are stored locally in this browser when using GitHub Pages.</p><div class="form-actions"><button type="button" class="secondary-btn" data-action="clear-local-data">Clear local data</button><button type="button" class="primary-btn" data-action="close-modal">Done</button></div></div></div></div>'; }
function saveLocalState() { localStorage.setItem('habit-arena-state', JSON.stringify(state)); }
function getLocalState() { try { return JSON.parse(localStorage.getItem('habit-arena-state')) || null; } catch { return null; } }
function currentPlayer(player, user = state?.user) { return Boolean(user) && (player.userId === user.id || player.you === true && !player.userId && player.name === user.name); }
function rankRooms(rooms, user = state?.user) { rooms.forEach(room => { room.leaderboard.sort((left, right) => right.score - left.score || right.streak - left.streak || left.name.localeCompare(right.name)); room.leaderboard.forEach((player, index) => { if (currentPlayer(player, user)) { room.yourRank = index + 1; room.yourStreak = player.streak; } }); }); return rooms; }
function renderLeaderboard() { const players = new Map(); state.rooms.forEach(room => room.leaderboard.forEach(player => { const key = player.userId || `${player.name}-${player.initials}`; const existing = players.get(key) || { ...player, score: 0, streak: 0, rooms: 0 }; existing.score += player.score; existing.streak = Math.max(existing.streak, player.streak); existing.rooms += 1; players.set(key, existing); })); const ranked = [...players.values()].sort((left, right) => right.score - left.score || right.streak - left.streak || left.name.localeCompare(right.name)); app.innerHTML = `${layoutHeading('ALL ARENAS', 'The leaderboard.', 'Every point counts across the rooms you play in.') }<div class="panel global-leaderboard"><div class="panel-title"><h2>Top competitors</h2><span>LIVE SYNC</span></div><div class="leader-header"><span>#</span><span>Competitor</span><span>Score</span><span>Rooms</span></div>${ranked.map((player, index) => `<div class="leader-row ${currentPlayer(player) ? 'you' : ''}"><span class="leader-rank">${index + 1}</span><span class="leader-name"><span class="avatar ${currentPlayer(player) ? 'avatar-coral' : index % 2 ? 'avatar-blue' : 'avatar-lime'}">${player.initials}</span>${player.name}${currentPlayer(player) ? ' (you)' : ''}</span><span class="leader-score">${player.score}</span><span class="leader-streak">${player.rooms}</span></div>`).join('')}</div>`; }
function joinRoomLocally(roomId) { const room = state.rooms.find(item => item.id === roomId); if (!room) throw new Error('Room not found'); if (room.leaderboard.some(currentPlayer)) return room; if (room.leaderboard.length >= room.maxParticipants) throw new Error('This room is full'); room.participants = room.leaderboard.length + 1; room.leaderboard.push({ userId: state.user.id, name: state.user.name, initials: state.user.initials, score: 0, streak: 0, you: true }); saveLocalState(); return room; }
async function request(url, options) {
  try {
    const requestOptions = { headers: { 'Content-Type': 'application/json' }, ...options };
    if ((url === '/api/rooms' || url === '/api/check-in') && options?.body) requestOptions.body = JSON.stringify({ ...JSON.parse(options.body), user: getIdentity() });
    const response = await fetch(url, requestOptions);
    const body = await response.json();
    if (!response.ok) throw new Error(body.error || 'Something went wrong');
    if (url === '/api/state' && !options) { const identity = getIdentity(); if (identity) body.user = { ...body.user, ...identity }; rankRooms(body.rooms, body.user); }
    return body;
  } catch (error) {
    if (url === '/api/state' && !options) {
      const stored = getLocalState();
      if (stored) return stored;
      return fetch('./data.json').then(response => response.json()).then(body => { const identity = getIdentity(); if (identity) body.user = { ...body.user, ...identity }; rankRooms(body.rooms, body.user); localStorage.setItem('habit-arena-state', JSON.stringify(body)); return body; });
    }
    if (url === '/api/habits' && options?.method === 'POST') { const body = JSON.parse(options.body); return { id: `habit-${Date.now()}`, name: body.name.trim(), frequency: body.frequency || 'Daily', streak: 0, bestStreak: 0, totalCheckins: 0, color: 'coral', checkedToday: false, history: [false, false, false, false, false, false, false] }; }
    if (url === '/api/rooms' && options?.method === 'POST') { const body = JSON.parse(options.body); return { id: `room-${Date.now()}`, name: body.name.trim(), topic: body.topic.trim(), status: 'waiting', daysLeft: Number(body.days) || 14, totalDays: Number(body.days) || 14, pot: (Number(body.entryFee) || 0) * (Number(body.maxParticipants) || 8), participants: 1, maxParticipants: Number(body.maxParticipants) || 8, yourRank: 1, yourStreak: 0, checkedToday: false, color: 'yellow', leaderboard: [{ userId: state.user.id, name: state.user.name, initials: state.user.initials, score: 0, streak: 0, you: true }] }; }
    if (url === '/api/check-in' && options?.method === 'POST') { const body = JSON.parse(options.body); const collection = body.type === 'habit' ? state.habits : state.rooms; const item = collection.find(entry => entry.id === body.id); if (!item) throw new Error('Item not found'); if (item.checkedToday) throw new Error('Already checked in today'); item.checkedToday = true; if (body.type === 'habit') { item.streak += 1; item.totalCheckins += 1; item.history[item.history.length - 1] = true; } else { item.yourStreak += 1; const player = item.leaderboard.find(currentPlayer); if (player) { player.score += 1; player.streak += 1; } rankRooms([item]); } state.activity.unshift({ text: `You checked in to ${item.name}`, time: 'Just now', type: 'check' }); state.activity = state.activity.slice(0, 6); saveLocalState(); return { item, user: state.user, activity: state.activity }; }
    if (url.startsWith('/api/rooms/') && url.endsWith('/join') && options?.method === 'POST') return joinRoomLocally(url.split('/')[3]);
    throw error;
  }
}
function money(value) { return `${value.toLocaleString()} pts`; }
function setView(view) { activeView = view; activeRoomId = null; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); render(); }
function render() { if (!state) return; if (activeView === 'rooms') return renderRooms(); if (activeView === 'habits') return renderHabits(); if (activeView === 'leaderboard') return renderLeaderboard(); renderOverview(); }
function layoutHeading(kicker, title, copy, action = '') { return `<div class="heading-row"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><div class="date-label">SATURDAY, SEPTEMBER 12, 2026</div></div><div><p>${copy}</p>${action}</div></div>`; }
function renderOverview() {
  const [focus, second] = state.rooms;
  app.innerHTML = `${layoutHeading('YOUR COMMAND CENTER', 'Make today count.', 'Every check-in is a vote for the person you want to become. Your arena is waiting.', '<button class="primary-btn" data-action="create-room">+ Start a room</button>')}
    <div class="grid-top"><article class="feature-room" data-action="open-room" data-id="${focus.id}"><span class="tag">● Live now · ${focus.daysLeft} days left</span><h2>${focus.name}</h2><p>${focus.topic}</p><div class="room-bottom"><div class="pot-number">${money(focus.pot)}<small>ON THE LINE · ${focus.participants} PLAYERS</small></div><button class="primary-btn">Enter room →</button></div></article><section class="panel stats-panel"><div class="panel-title"><h2>Your season so far</h2><span>UPDATED LIVE</span></div><div class="stat-row"><div class="stat-symbol">♨</div><div><span class="stat-value">${state.user.bestStreak}</span><span class="stat-name">Best streak</span></div><span class="stat-change">+4%</span></div><div class="stat-row"><div class="stat-symbol">✦</div><div><span class="stat-value">${state.user.wins}</span><span class="stat-name">Arena wins</span></div><span class="stat-change">+2 this mo.</span></div><div class="stat-row"><div class="stat-symbol">◉</div><div><span class="stat-value">${state.user.points.toLocaleString()}</span><span class="stat-name">Points balance</span></div><span class="stat-change">+120 pts</span></div></section></div>
    <div class="section-head"><h2>Active arenas <span class="eyebrow">/ ${state.rooms.length}</span></h2><button class="link-btn" data-view="rooms">View all →</button></div><div class="room-list">${state.rooms.map(roomCard).join('')}</div>
    <div class="section-head"><h2>Solo habits <span class="eyebrow">/ ${state.habits.length}</span></h2><button class="link-btn" data-view="habits">Manage habits →</button></div><div class="habits-grid">${state.habits.map(habitCard).join('')}</div>
    <div class="section-head"><h2>Live feed</h2><span class="eyebrow">JUST NOW</span></div><div class="activity">${state.activity.map(activityItem).join('')}</div>`;
}
function roomCard(room) { return `<article class="room-card" data-action="open-room" data-id="${room.id}"><div class="room-card-head"><div><h3>${room.name}</h3><p>${room.topic}</p></div><span class="status ${room.status}">${room.status === 'live' ? '● Live' : 'Waiting'}</span></div><div class="room-card-bottom"><div class="room-metric">${money(room.pot)}<small>${room.daysLeft} days remaining</small></div><div class="rank-badge">#${room.yourRank}<small>your current rank</small></div></div></article>`; }
function habitCard(habit) { return `<article class="habit-card"><div class="habit-top"><span class="tag">Solo / ${habit.frequency}</span><span class="eyebrow">${habit.totalCheckins} logs</span></div><h3>${habit.name}</h3><p>Consistency compounds quietly.</p><div class="streak">${habit.streak} <small>day streak</small></div><div class="week">${habit.history.map((done, i) => `<span class="day ${done ? 'done' : ''}">${['M','T','W','T','F','S','S'][i]}</span>`).join('')}</div><button class="check-btn ${habit.checkedToday ? 'done' : ''}" data-action="check-in" data-type="habit" data-id="${habit.id}">${habit.checkedToday ? '✓ Checked in today' : 'Log today’s progress'}</button></article>`; }
function activityItem(item) { return `<div class="activity-item"><span class="activity-icon">${icons[item.type] || '•'}</span><span>${item.text}</span><span class="activity-time">${item.time}</span></div>`; }
function renderRooms() { app.innerHTML = `${layoutHeading('YOUR COMPETITIONS', 'The arenas.', 'Small rooms. Real friends. A reason to show up.') }<div class="section-head" style="margin-top:0"><h2>Active arenas</h2><button class="primary-btn" data-action="create-room">+ Create room</button></div><div class="room-list">${state.rooms.map(roomCard).join('')}</div><div class="section-head"><h2>How it works</h2></div><div class="panel" style="padding:22px; display:grid; grid-template-columns:repeat(3,1fr); gap:22px"><div><span class="eyebrow">01 / INVITE</span><p>Start a private room and pull your people in.</p></div><div><span class="eyebrow">02 / CHECK IN</span><p>Show up once a day. Your rank follows.</p></div><div><span class="eyebrow">03 / COLLECT</span><p>Finish strong and split the pot by rank.</p></div></div>`; }
function renderHabits() { app.innerHTML = `${layoutHeading('PRIVATE MODE', 'Solo, for now.', 'Build trust with yourself before you put a spotlight on the habit.', '<button class="primary-btn" data-action="create-habit">+ New habit</button>')}<div class="habits-grid">${state.habits.map(habitCard).join('')}</div><div class="empty-state" style="margin-top:18px">Your private habits stay yours. Graduate one into an arena whenever you are ready.</div>`; }
function renderRoom(room) { activeRoomId = room.id; app.innerHTML = `<button class="link-btn" data-view="overview">← Back to overview</button><div class="section-head" style="margin-top:20px"><div><div class="eyebrow">LIVE ARENA / ${room.daysLeft} DAYS LEFT</div><h1>${room.name}</h1></div><button class="secondary-btn" data-action="share-invite" data-id="${room.id}">⤴ Share invite</button></div><div class="room-detail"><section class="detail-hero"><span class="tag">${room.status === 'live' ? '● In progress' : 'Waiting for rivals'}</span><h2>${room.topic}</h2><p>Everyone checks in once a day. No excuses, no disappearing acts.</p><div class="detail-meta"><div><strong>${money(room.pot)}</strong><span>current pot</span></div><div><strong>${room.participants}/${room.maxParticipants}</strong><span>players</span></div><div><strong>#${room.yourRank}</strong><span>your rank</span></div></div></section><section class="leaderboard"><div class="panel-title"><h2>Live leaderboard</h2><span>LIVE SYNC</span></div><div class="leader-header"><span>#</span><span>Competitor</span><span>Score</span><span>Streak</span></div>${(room.leaderboard.length ? room.leaderboard : [{name:'Waiting for rivals', initials:'?', score:0, streak:0}]).map((player, index) => `<div class="leader-row ${currentPlayer(player) ? 'you' : ''}"><span class="leader-rank">${index + 1}</span><span class="leader-name"><span class="avatar ${currentPlayer(player) ? 'avatar-coral' : index % 2 ? 'avatar-blue' : 'avatar-lime'}">${player.initials}</span>${player.name}${currentPlayer(player) ? ' (you)' : ''}</span><span class="leader-score">${player.score}</span><span class="leader-streak">${player.streak}d</span></div>`).join('')}</section></div><div class="panel" style="margin-top:18px; padding:20px; display:flex; justify-content:space-between; align-items:center; gap:15px"><div><div class="eyebrow">TODAY'S MOVE</div><strong>${room.checkedToday ? 'You showed up today.' : 'Your next point is waiting.'}</strong><p style="margin:5px 0 0;color:var(--muted);font-size:11px">One check-in takes you one step closer to the top.</p></div><button class="primary-btn ${room.checkedToday ? 'done' : ''}" data-action="check-in" data-type="room" data-id="${room.id}">${room.checkedToday ? '✓ Checked in' : 'Log today’s progress'}</button></div>`; }
async function joinRoom(id) { try { const room = await request(`/api/rooms/${encodeURIComponent(id)}/join`, { method: 'POST', body: JSON.stringify({ user: getIdentity() }) }); rankRooms([room]); const index = state.rooms.findIndex(item => item.id === id); if (index >= 0) state.rooms[index] = room; else state.rooms.unshift(room); renderRoom(room); toast(`Joined ${room.name}.`); } catch (error) { const room = state.rooms.find(item => item.id === id); if (room) renderRoom(room); else toast(error.message); } }
async function syncState() { try { const nextState = await request('/api/state'); const identity = getIdentity(); if (identity) nextState.user = { ...nextState.user, ...identity }; rankRooms(nextState.rooms); state = nextState; document.querySelector('#room-count').textContent = state.rooms.length; document.querySelector('#sidebar-points').textContent = state.user.points.toLocaleString(); if (activeRoomId) { const room = state.rooms.find(item => item.id === activeRoomId); if (room) renderRoom(room); } else render(); } catch { /* Keep the last known state during a temporary network gap. */ } }
async function shareInvite(id) {
  const room = state.rooms.find(item => item.id === id);
  if (!room) return toast('Room not found.');
  const inviteUrl = new URL(window.location.href);
  inviteUrl.search = `room=${encodeURIComponent(room.id)}`;
  try {
    if (navigator.share) {
      await navigator.share({ title: `Join ${room.name}`, text: `Join my Habit Arena room: ${room.name}`, url: inviteUrl.href });
    } else {
      await navigator.clipboard.writeText(inviteUrl.href);
      toast('Invite link copied.');
    }
  } catch (error) {
    if (error.name !== 'AbortError') toast('Could not share the invite.');
  }
}
function openModal(type) { const isRoom = type === 'room'; const isSignIn = type === 'sign-in'; const title = isSignIn ? 'Welcome back' : isRoom ? 'Start a new arena' : 'Create solo habit'; const formId = isSignIn ? 'sign-in-form' : isRoom ? 'room-form' : 'habit-form'; const formContent = isSignIn ? '<label>Email address<input name="email" type="email" placeholder="you@example.com" autocomplete="email" required></label><label>Password<input name="password" type="password" placeholder="Enter your password" autocomplete="current-password" required></label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center;gap:8px;text-transform:none;font-family:Space Grotesk,sans-serif;font-size:12px"><input name="remember" type="checkbox" style="width:auto" checked> Keep me signed in</label>' : isRoom ? '<label>Room name<input name="name" placeholder="e.g. The Early Birds" required></label><label>What are you competing on?<input name="topic" placeholder="e.g. No snooze before 8am" required></label><div class="form-row"><label>Duration<select name="days"><option value="7">7 days</option><option value="14" selected>14 days</option><option value="30">30 days</option></select></label><label>Max players<input name="maxParticipants" type="number" min="2" max="20" value="8"></label></div><label>Entry fee <span style="color:var(--muted)">(virtual points)</span><input name="entryFee" type="number" min="0" value="80"></label>' : '<label>What habit are you building?<input name="name" placeholder="e.g. Journal for 10 minutes" required></label><label>Target frequency<select name="frequency"><option>Daily</option><option>5 days / week</option><option>3 days / week</option></select></label>'; const submitLabel = isSignIn ? 'Sign in →' : `Create ${isRoom ? 'arena' : 'habit'} →`; document.querySelector('#modal-root').innerHTML = `<div class="modal-backdrop" data-action="close-modal"><div class="modal" onclick="event.stopPropagation()"><div class="modal-header"><h2>${title}</h2><button class="close-btn" data-action="close-modal">×</button></div><form class="form" id="${formId}">${formContent}<div class="form-actions"><button type="button" class="secondary-btn" data-action="close-modal">Cancel</button><button class="primary-btn">${submitLabel}</button></div></form></div></div>`; }
function toast(message) { const element = document.querySelector('#toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2600); }
async function checkIn(type, id) { try { const result = await request('/api/check-in', { method: 'POST', body: JSON.stringify({ type, id }) }); if (type === 'habit') Object.assign(state.habits.find(item => item.id === id), result.item); else Object.assign(state.rooms.find(item => item.id === id), result.item); state.activity = result.activity; toast('Logged. Your consistency just got louder.'); render(); } catch (error) { toast(error.message); } }

document.addEventListener('click', event => { const actionElement = event.target.closest('[data-action]'); const action = actionElement?.dataset.action; const backdrop = event.target.closest('.modal-backdrop'); if (action === 'close-modal' && actionElement === backdrop && !event.target.classList.contains('modal-backdrop')) { event.stopImmediatePropagation(); return; } if ((action === 'close-modal' && actionElement !== backdrop) || event.target.classList.contains('modal-backdrop')) document.querySelector('#modal-root').innerHTML = ''; }, true);
document.addEventListener('click', event => { const action = event.target.closest('[data-action]')?.dataset.action; const view = event.target.closest('[data-view]')?.dataset.view; if (view) return setView(view); if (action === 'create-room') return openModal('room'); if (action === 'create-habit') return openModal('habit'); if (action === 'sign-in') return openProfileModal(); if (action === 'settings') return openSettingsModal(); if (action === 'sign-out') { localStorage.removeItem(identityKey); localStorage.removeItem('habit-arena-state'); document.querySelector('#modal-root').innerHTML = ''; toast('Identity reset.'); return openIdentityModal(); } if (action === 'clear-local-data') { localStorage.removeItem('habit-arena-state'); toast('Local activity cleared.'); return document.querySelector('#modal-root').innerHTML = ''; } if (action === 'close-modal') return document.querySelector('#modal-root').innerHTML = ''; if (event.target.classList.contains('modal-backdrop')) return document.querySelector('#modal-root').innerHTML = ''; if (action === 'check-in') return checkIn(event.target.closest('[data-action]').dataset.type, event.target.closest('[data-action]').dataset.id); if (action === 'share-invite') return shareInvite(event.target.closest('[data-action]').dataset.id); if (action === 'open-room') { const room = state.rooms.find(item => item.id === event.target.closest('[data-action]').dataset.id); return renderRoom(room); } if (action === 'notifications') return toast('You are all caught up.'); });
document.addEventListener('keydown', event => { if (event.key === 'Escape') document.querySelector('#modal-root').innerHTML = ''; });
document.addEventListener('submit', event => { if (!event.target.matches('#identity-form')) return; event.preventDefault(); const identity = createIdentity(new FormData(event.target).get('name')); applyIdentity(identity); document.querySelector('#modal-root').innerHTML = ''; toast(`Welcome, ${identity.name}.`); if (inviteRoom()) joinRoom(inviteRoom()); });
document.addEventListener('submit', event => { if (!event.target.matches('#profile-form')) return; event.preventDefault(); const identity = createIdentity(new FormData(event.target).get('name')); applyIdentity(identity); document.querySelector('#modal-root').innerHTML = ''; toast('Profile updated.'); });
document.addEventListener('submit', async event => { if (!event.target.matches('#room-form, #habit-form, #sign-in-form')) return; event.preventDefault(); if (event.target.id === 'sign-in-form') { document.querySelector('#modal-root').innerHTML = ''; toast('Signed in successfully.'); return; } const form = new FormData(event.target); const isRoom = event.target.id === 'room-form'; try { const item = await request(isRoom ? '/api/rooms' : '/api/habits', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); (isRoom ? state.rooms : state.habits).unshift(item); saveLocalState(); document.querySelector('#modal-root').innerHTML = ''; toast(`${isRoom ? 'Arena' : 'Habit'} created.`); render(); } catch (error) { toast(error.message); } });
async function init() { try { state = await request('/api/state'); const identity = getIdentity(); if (identity) applyIdentity(identity); document.querySelector('#room-count').textContent = state.rooms.length; document.querySelector('#sidebar-points').textContent = state.user.points.toLocaleString(); render(); if (inviteRoom() && identity) await joinRoom(inviteRoom()); if (!identity) openIdentityModal(); } catch (error) { app.innerHTML = `<div class="empty-state">Could not connect to the arena server. ${error.message}</div>`; } }
init();
setInterval(syncState, 3000);
